### ISSUE TITLE
vite环境使用js_base64报下面的错

### ISSUE THREAD

**Issue by coderja** [dankogai/js-base64#161]
TypeError: buffer is not a constructor
    at _encode (base64.js:96:24)
    at Object.encode (base64.js:102:30)
    at login (loginAPI.js?t=1671159346988:5:24)
    at user.js?t=1671159346988:87:11
    at new Promise (<anonymous>)
    at Store2.Login (user.js?t=1671159346988:85:14)
    at Array.wrappedActionHandler (vuex.esm.js:747:23)
    at Store2.dispatch (vuex.esm.js:438:13)
    at Store2.boundDispatch [as dispatch] (vuex.esm.js:332:21)
    at index.vue:210:1

**Comment by dankogai** [comment]
Would you also file the report in English?  Would you give me more information than a stack trace of your app?  IMHO it is caller's issue than this module.
