### ISSUE TITLE
Don't pass global object as argument

### ISSUE THREAD

**Issue by ematveyev** [dankogai/js-base64#32]
Please, don't pass global object as argument here https://github.com/dankogai/js-base64/blob/master/base64.js#L11
Build with Babel fails here with error 

```
Requiring external module babel-core/register
/Users/meu/web/node_modules/js-base64/base64.js:16
    var _Base64 = global.Base64;
                        ^

TypeError: Cannot read property 'Base64' of undefined
    at /Users/meu/web/node_modules/js-base64/base64.js:14:25
    at Object.<anonymous> (/Users/meu/web/node_modules/js-base64/base64.js:194:2)
    at Module._compile (module.js:425:26)
    at normalLoader (/Users/meu/web/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/meu/web/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/meu/web/node_modules/postcss/lib/map-generator.js:5:15)
```

**Comment by cuiyajie** [comment]
Yes, eshint also failed with the error  'Base64' not defined.

**Comment by FuGardenia** [comment]
I have the same error

**Comment by FuGardenia** [comment]
use `import {Base64} from "js-base64"` save the error

**Comment by itriy** [comment]
who knows, how to fix it?

**Comment by ComLock** [comment]
Both 
import { Base64 } from '/node_modules/js-base64/base64.js';
and
import { Base64 } from '/node_modules/js-base64/base64.min.js';

Give me the following error:
TypeError: Cannot get property "Base64" of null

On line 14
var _Base64 = global.Base64;

In other words global is null...

**Comment by developerdizzle** [comment]
This is also causing some Jest tests to blow up for me.

**Comment by holynova** [comment]
I met this problem too.
This project has not been updated since July 2015 , it is 2017-6-15 now ,will the author solve this after this long time? 
@dankogai

**Comment by dankogai** [comment]
Should be fixed in https://github.com/dankogai/js-base64/commit/2bfbc30e8821350af562277f47610542fc568be3.
