### ISSUE TITLE
Does not compile on Fedora25

### ISSUE THREAD

**Issue by ip6li** [dankogai/js-base64#47]
Using this package.json:

    {
      "name": "test",
      "version": "0.0.1",
      "license": "AGPL-3.0",
      "private": true,
      "dependencies": {
        "intl": "~1.2.5",
        "base64": "~2.1.0"
      },
      "devDependencies": {
        "jshint": "^2.9.2"
      }
    }

$ LANG=C npm install

    > base64@2.1.0 install /home/cf/Development/test/node_modules/base64
    > node-gyp rebuild
    
    make: Verzeichnis „/home/cf/Development/test/node_modules/base64/build“ wird betreten
      CXX(target) Release/obj.target/base64/base64.o
    ../base64.cc: In Funktion »v8::Handle<v8::Value> VException(const char*)«:
    ../base64.cc:13:17: Fehler: »v8::HandleScope::HandleScope()« is protected within this context
         HandleScope scope;
                     ^~~~~
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:904:13: Anmerkung: declared protected here
       V8_INLINE HandleScope() {}
                 ^~~~~~~~~~~
    ../base64.cc:14:44: Fehler: »New« ist kein Element von »v8::String«
         return ThrowException(Exception::Error(String::New(msg)));
                                                ^~~~~~
    ../base64.cc:14:61: Fehler: »ThrowException« wurde in diesem Gültigkeitsbereich nicht definiert
         return ThrowException(Exception::Error(String::New(msg)));
                                                                 ^
    ../base64.cc: Im globalen Gültigkeitsbereich:
    ../base64.cc:122:29: Fehler: »Arguments« bezeichnet keinen Typ
     base64_encode_binding(const Arguments &args)
                                 ^~~~~~~~~
    ../base64.cc: In Funktion »v8::Handle<v8::Value> base64_encode_binding(const int&)«:
    ../base64.cc:124:17: Fehler: »v8::HandleScope::HandleScope()« is protected within this context
         HandleScope scope;
                     ^~~~~
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:904:13: Anmerkung: declared protected here
       V8_INLINE HandleScope() {}
                 ^~~~~~~~~~~
    ../base64.cc:127:14: Fehler: Abfrage des Elementes »Length« in »args«, das vom Nicht-Klassentyp »const int« ist
         if (args.Length() != 1)
                  ^~~~~~
    ../base64.cc:130:35: Fehler: ungültige Typen »const int[int]« für Feldindex
         if (Buffer::HasInstance(args[0])) {
                                       ^
    ../base64.cc:131:47: Fehler: ungültige Typen »const int[int]« für Feldindex
             v8::Handle<v8::Object> buffer = args[0]->ToObject();
                                                   ^
    ../base64.cc:137:20: Fehler: ungültige Typen »const int[int]« für Feldindex
         else if (args[0]->IsString()) {
                        ^
    ../base64.cc:138:40: Fehler: ungültige Typen »const int[int]« für Feldindex
             String::Utf8Value v8str (args[0]->ToString());
                                            ^
    ../base64.cc:144:25: Fehler: »New« ist kein Element von »v8::String«
         Local<String> ret = String::New(str);
                             ^~~~~~
    ../base64.cc:146:18: Fehler: »class v8::HandleScope« has no member named »Close«
         return scope.Close(ret);
                      ^~~~~
    ../base64.cc: Im globalen Gültigkeitsbereich:
    ../base64.cc:150:29: Fehler: »Arguments« bezeichnet keinen Typ
     base64_decode_binding(const Arguments &args)
                                 ^~~~~~~~~
    ../base64.cc: In Funktion »v8::Handle<v8::Value> base64_decode_binding(const int&)«:
    ../base64.cc:152:17: Fehler: »v8::HandleScope::HandleScope()« is protected within this context
         HandleScope scope;
                     ^~~~~
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:904:13: Anmerkung: declared protected here
       V8_INLINE HandleScope() {}
                 ^~~~~~~~~~~
    ../base64.cc:155:14: Fehler: Abfrage des Elementes »Length« in »args«, das vom Nicht-Klassentyp »const int« ist
         if (args.Length() < 1)
                  ^~~~~~
    ../base64.cc:160:35: Fehler: ungültige Typen »const int[int]« für Feldindex
         if (Buffer::HasInstance(args[0])) { // buffer
                                       ^
    ../base64.cc:161:47: Fehler: ungültige Typen »const int[int]« für Feldindex
             v8::Handle<v8::Object> buffer = args[0]->ToObject();
                                                   ^
    ../base64.cc:170:9: Fehler: »AsciiValue« ist kein Element von »v8::String«
             String::AsciiValue b64data(args[0]->ToString());
             ^~~~~~
    ../base64.cc:171:34: Fehler: »b64data« wurde in diesem Gültigkeitsbereich nicht definiert
             decoded = base64_decode(*b64data, b64data.length(), &outlen);
                                      ^~~~~~~
    ../base64.cc:174:14: Fehler: Abfrage des Elementes »Length« in »args«, das vom Nicht-Klassentyp »const int« ist
         if (args.Length() > 1 && args[1]->IsString()) {
                  ^~~~~~
    ../base64.cc:174:36: Fehler: ungültige Typen »const int[int]« für Feldindex
         if (args.Length() > 1 && args[1]->IsString()) {
                                        ^
    ../base64.cc:175:9: Fehler: »AsciiValue« ist kein Element von »v8::String«
             String::AsciiValue flag(args[1]->ToString());
             ^~~~~~
    ../base64.cc:176:29: Fehler: »flag« wurde in diesem Gültigkeitsbereich nicht definiert
             if (strcmp("utf8", *flag) == 0) encflag = UTF8;
                                 ^~~~
    ../base64.cc:179:55: Warnung: »v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)« ist veraltet: Use Encode(isolate, ...) [-Wdeprecated-declarations]
         Local<Value> ret = Encode(decoded, outlen, encflag);
                                                           ^
    In file included from ../base64.cc:5:0:
    /home/cf/.node-gyp/6.3.1/include/node/node.h:319:45: Anmerkung: hier deklariert
                     inline v8::Local<v8::Value> Encode(
                                                 ^
    /home/cf/.node-gyp/6.3.1/include/node/node.h:66:42: Anmerkung: in Definition des Makros »NODE_DEPRECATED«
         __attribute__((deprecated(message))) declarator
                                              ^~~~~~~~~~
    ../base64.cc:182:18: Fehler: »class v8::HandleScope« has no member named »Close«
         return scope.Close(ret);
                      ^~~~~
    ../base64.cc: In Funktion »void init(v8::Handle<v8::Object>)«:
    ../base64.cc:187:17: Fehler: »v8::HandleScope::HandleScope()« is protected within this context
         HandleScope scope;
                     ^~~~~
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:904:13: Anmerkung: declared protected here
       V8_INLINE HandleScope() {}
                 ^~~~~~~~~~~
    ../base64.cc:188:17: Fehler: »New« ist kein Element von »v8::String«
         target->Set(String::New("encode"), FunctionTemplate::New(base64_encode_binding)->GetFunction());
                     ^~~~~~
    ../base64.cc:188:83: Fehler: keine passende Funktion für Aufruf von »v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))«
         target->Set(String::New("encode"), FunctionTemplate::New(base64_encode_binding)->GetFunction());
                                                                                       ^
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:4452:34: Anmerkung: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
       static Local<FunctionTemplate> New(
                                      ^~~
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:4452:34: Anmerkung:   keine bekannte Umwandlung für Argument 1 von »v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}« nach »v8::Isolate*«
    ../base64.cc:189:17: Fehler: »New« ist kein Element von »v8::String«
         target->Set(String::New("decode"), FunctionTemplate::New(base64_decode_binding)->GetFunction());
                     ^~~~~~
    ../base64.cc:189:83: Fehler: keine passende Funktion für Aufruf von »v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))«
         target->Set(String::New("decode"), FunctionTemplate::New(base64_decode_binding)->GetFunction());
                                                                                       ^
    In file included from ../base64.cc:4:0:
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:4452:34: Anmerkung: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
       static Local<FunctionTemplate> New(
                                      ^~~
    /home/cf/.node-gyp/6.3.1/include/node/v8.h:4452:34: Anmerkung:   keine bekannte Umwandlung für Argument 1 von »v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}« nach »v8::Isolate*«
    base64.target.mk:86: die Regel für Ziel „Release/obj.target/base64/base64.o“ scheiterte
    make: *** [Release/obj.target/base64/base64.o] Fehler 1
    make: Verzeichnis „/home/cf/Development/test/node_modules/base64/build“ wird verlassen
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/cf/Development/node-v6.3.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    gyp ERR! System Linux 4.10.10-200.fc25.x86_64
    gyp ERR! command "/home/cf/Development/node-v6.3.1-linux-x64/bin/node" "/home/cf/Development/node-v6.3.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/cf/Development/test/node_modules/base64
    gyp ERR! node -v v6.3.1
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok 
    npm ERR! Linux 4.10.10-200.fc25.x86_64
    npm ERR! argv "/home/cf/Development/node-v6.3.1-linux-x64/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.3.1
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    
    npm ERR! base64@2.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the base64@2.1.0 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the base64 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs base64
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls base64
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/cf/Development/test/npm-debug.log

Fedora 25 installation uses following GCC/C++ packages:
    
gcc-c++-6.3.1-1.fc25.x86_64
libstdc++-6.3.1-1.fc25.x86_64
libsigc++20-2.10.0-1.fc25.x86_64
libstdc++-devel-6.3.1-1.fc25.x86_64
gcc-6.3.1-1.fc25.x86_64
gcc-c++-6.3.1-1.fc25.x86_64
gcc-gdb-plugin-6.3.1-1.fc25.x86_64
libgcc-6.3.1-1.fc25.x86_64

If js-base64 assumes existence of specific packages, this should be documented.

**Comment by ip6li** [comment]
Seems not to be used in package.js.
