### ISSUE TITLE
base64 is not a function

### ISSUE THREAD

**Issue by yanickrochon** [dankogai/js-base64#55]
Just got this when running Gulp on a third party project :

```
TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at /path/to/project/node_modules/js-base64/base64.js:148:34
    at Object.decode (/path/to/project/node_modules/js-base64/base64.js:156:16)
    at PreviousMap.decodeInline (/path/to/project/node_modules/postcss/lib/previous-map.js:106:35)
    at PreviousMap.loadMap (/path/to/project/node_modules/postcss/lib/previous-map.js:138:25)

    at new PreviousMap (/path/to/project/node_modules/postcss/lib/previous-map.js:52:25)
    at new Input (/path/to/project/node_modules/postcss/lib/input.js:73:19)
    at parse (/path/to/project/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/path/to/project/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/path/to/project/node_modules/postcss/lib/processor.js:117:12)
    at DestroyableTransform._transform (/path/to/project/node_modules/gulp-autoprefixer/index.js:20:31)
    at DestroyableTransform.Transform._read (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
```

I am still investigating what can cause this, but since it affects this module, I concluded that perhaps someone more familiar with it may have an idea why or how to gracefully handle this better.

**Comment by yanickrochon** [comment]
Moving from node 4.2 to 6.11 solved it. Old project needed Node upgrade...
