### ISSUE TITLE
Unable to resolve module `buffer`...

### ISSUE THREAD

**Issue by joehdodd** [dankogai/js-base64#82]
I see someone opened this issue and it was closed because the package is supposed to detect React Native, but I'm still getting this issue with the last version of `js-base64` _and_ the latest version of React Native.

The only resolution is to install `buffer`.

**Comment by dankogai** [comment]
base64.js itself detects React Native and avoid using `Buffer` but chances are React Native wrongly (perhaps statically) thinks it depends on `Buffer` JUST BECAUSE `require('Buffer')` exists in the source file.  There are numerous such claims…

https://www.google.com/search?client=safari&rls=en&q=React+Native+Buffer+is+not+defined&ie=UTF-8&oe=UTF-8

**Comment by dankogai** [comment]
Okay.  I've run React Native myself and found it DOES USE node.js when run on iOS SIMULATOR via Metro Bundler (ugh!)

```
Scanning folders for symlinks in /Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules (16ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/dankogai/ZZZ_notm/work/reactnative/sample 


Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `buffer` from `/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/js-base64/base64.js`: Module `buffer` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:1306)
    at ResolutionRequest.resolveDependency (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/dankogai/ZZZ_notm/work/reactnative/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
```

<img width="598" alt="screen shot 2018-08-28 at 1 19 54" src="https://user-images.githubusercontent.com/68812/44672157-95b53d80-aa62-11e8-8ffc-d1454a9a8bd8.png">

**Comment by dankogai** [comment]
I've fixed it once for all.  Here is the code. `eval()` did the trick.

```javascript
// if node.js and NOT React Native, we use Buffer
    var buffer;
    if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = eval("require('buffer').Buffer");
        } catch (err) {
            buffer = undefined;
        }
    }
```

**Comment by joehdodd** [comment]
This is awesome. Thanks for taking a look! Go figure RN still uses Node in some capacity.
